name: Deploy Production (manual)
on:
  workflow_dispatch: {}   # manual button in Actions tab

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish to gh-pages (production)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./        # your built site directory
          exclude_assets: |
            .github
            .gitignore
            README.md
            LICENSE
